In [106]:
from sklearn import datasets
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import numpy as np
import math
from random import shuffle
from sklearn.metrics import accuracy_score, confusion_matrix

In [36]:
def load_data_set():
    data = datasets.load_iris()
    return data['data'], data['target']
print(load_data_set()[0])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [42]:
def euclidian_distance(x_target, x_base):
    dist = 0.0
    for i in range(len(x_target)):
        dist += (x_target[i] - x_base[i])**2
    return math.sqrt(dist)
#print(len([[1, 2,3]]))
euclidian_distance([2, 3, 4], [1, 5, 6])

3.0

In [105]:
list_tmp =[[2, 3], [6, 7], [3, 34], [24, 64], [1, 43]]
list_tmp = sorted(list_tmp, key=lambda x:x[0])
print(list_tmp)

[[1, 43], [2, 3], [3, 34], [6, 7], [24, 64]]


In [91]:
def split_data(x, y, split_ratio = 0.7):
    idx_list = [i for i in range(len(x))]
    shuffle(idx_list)
    x = x[idx_list, :]
    y = y[idx_list]
    split_index = int(len(x)*split_ratio)
    x_train = x[:split_index]
    x_test = x[split_index:]
    y_train = y[:split_index]
    y_test = y[split_index:]
    return x_train, y_train, x_test, y_test

In [98]:
def predict(X_test, x, y, k):
    '''
    x = np.asarray(x)
    y = np.asarray(y).reshape(-1,1)
    x = np.append(x, y,axis = 1 )
    print(np.shape(x))
    '''
    no_of_classes = len(set(y))
    print('No of classes: ', no_of_classes)
            
    results = []
    for sample in X_test:
        dist_metrics = []
        count ={}
        for i in set(y):
            count[i] =  0
        for i in range(len(x)):
            tmp_dist = euclidian_distance(sample, x[i])
            dist_metrics.append([tmp_dist]+ [y[i]])
        dist_metrics = sorted(dist_metrics, key = lambda x:x[0])
        dist_metrics = dist_metrics[:k]
        for dist_list in dist_metrics:
            count[dist_list[1]] += 1
#         print(dist_metrics)
#         print(count)
        res = max(count, key = count.get)
        results.append(res)
#         print('res: ', res)
    print(results)
    return results
# x, y = load_data_set()
# predict(predict([[1, 2, 3, 4]],x, y, 7))

In [108]:
def main():
    k = 3
    x, y = load_data_set()
    
    x_train, y_train, x_test, y_test = split_data(x, y)
    print(len(x_test))
    y_predict = predict(x_test, x_train, y_train, k)
    print('without normalize: ', accuracy_score(y_predict, y_test))
    from sklearn import preprocessing
    x = preprocessing.normalize(x)
    x_train, y_train, x_test, y_test = split_data(x, y)
    y_predict = predict(x_test, x_train, y_train, k)
    print('normalized data: ', accuracy_score(y_predict, y_test), 'confusion matrix:\n',confusion_matrix(y_test, y_predict) )
    
main()

45
No of classes:  3
[2, 2, 2, 0, 2, 2, 0, 1, 2, 2, 1, 1, 1, 1, 2, 2, 1, 0, 2, 2, 2, 0, 0, 0, 0, 0, 1, 1, 0, 2, 2, 1, 0, 0, 1, 2, 0, 0, 1, 1, 0, 0, 1, 1, 1]
without normalize:  0.9777777777777777
No of classes:  3
[2, 1, 1, 2, 2, 2, 0, 0, 0, 1, 1, 0, 2, 2, 0, 2, 0, 1, 2, 2, 1, 1, 1, 2, 2, 0, 0, 1, 2, 1, 1, 1, 1, 2, 2, 0, 1, 1, 2, 1, 0, 1, 1, 2, 2]
normalized data:  0.9333333333333333 confusion matrix:
 [[10  0  0]
 [ 0 16  1]
 [ 0  2 16]]
